version: 2

jobs:
  prep-and-docbuild:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/api-pages
    steps:
      #- run:
      #    name: check ssh
      #    command: ssh -v -oStrictHostKeyChecking=no git@github.com

      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm and build
          command: |
            sudo apt install build-essential python-pip
            sudo pip install pyyaml
            npm install
            mkdir -p dist/{apidoc,bootprint}
            npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/api-pages/node_modules

      - store_artifacts:
          path: ~/api-pages/dist
          destination: scan-test-results

      - save_cache:
          key: dist-cache-{{ "CIRCLE_BUILD_NUM" }}
          paths:
            - ~/api-pages/dist

  ghpages:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/api-pages
    steps:
      - checkout
      - restore_cache:
          key: dist-cache-{{ "CIRCLE_BUILD_NUM" }}
      - run:
          name: prep
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            cp index.html new.html
            git checkout gh-pages
            mv new.html index.html
            cp -r dist/* samples/
            git add index.html && git add samples && git commit -m "ci build [$CIRCLE_BUILD_NUM] commit"
            git push origin gh-pages

workflows:
  version: 2
  api_docs:
    jobs:
      - prep-and-docbuild
      - ghpages:
          requires:
            - prep-and-docbuild
          filters:
            branches:
              ignore:
                - gh-pages
