version: 2

jobs:
  prep-and-docbuild:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/api-pages
    steps:
      #- run:
      #    name: check ssh
      #    command: ssh -v -oStrictHostKeyChecking=no git@github.com

      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install npm
          command: |
            npm install
            mkdir -p dist/{apidoc,bootprint}

      - run:
          name: build npm
          command: |
            npm run aglio
            npm run bootprint
            npm run raml
            npm run apidoc

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/api-pages/node_modules

      - store_artifacts:
          path: ~/api-pages/dist
          destination: scan-test-results

      - save_cache:
          key: dist-cache-{{ "CIRCLE_BUILD_NUM" }}
          paths:
            - ~/api-pages/dist
            - ~/api-pages/bootprint

  python-build:
    docker:
      - image: circleci/python:3.8.0
    working_directory: ~/api-pages
    steps:
      - checkout

      - run:
          name: Install packages
          command: |
            #sudo apt install build-essential python-pip
            sudo apt -y install python-pip
            sudo pip install pyyaml

      - restore_cache:
          key: dist-cache-{{ "CIRCLE_BUILD_NUM" }}

      - run:
          name: build npm
          command: cat bootprint/swagger.yaml | python swagger-ui/to-ui-html.py > dist/swagger-ui.html
          # SHOULD use npm run swagger-ui

      - save_cache:
          key: dist-cache-{{ "CIRCLE_BUILD_NUM" }}
          paths:
            - ~/api-pages/dist
            - ~/api-pages/bootprint

  ghpages:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/api-pages
    steps:
      - checkout

      - restore_cache:
          key: dist-cache-{{ "CIRCLE_BUILD_NUM" }}

      - run:
          name: prep
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git checkout gh-pages

      - add_ssh_keys:
          fingerprints:
            - "93:4f:69:48:bc:76:33:06:fc:b9:22:9a:c5:d3:f6:a7"

      - run:
          name: prep
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            cp index.html new.html
            git checkout gh-pages
            mv new.html index.html
            cp -r dist/* samples/
            git add index.html && git add samples && git commit -m "ci build [$CIRCLE_BUILD_NUM] commit"
            git push origin gh-pages

workflows:
  version: 2
  api_docs:
    jobs:
      - prep-and-docbuild:
          filters:
            branches:
              ignore:
                - gh-pages

      - python-build:
          requires:
            - prep-and-docbuild
          filters:
            branches:
              ignore:
                - gh-pages

      - ghpages:
          requires:
            - prep-and-docbuild
            - python-build
          filters:
            branches:
              ignore:
                - gh-pages
